name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build and package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run package

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: beat-and-teach-${{ matrix.os }}
          path: release/build/
          retention-days: 30
